/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Favorites: typeof import('./components/FavoritesList.vue')['default']
    FavoritesList: typeof import('./components/FavoritesList.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Index: typeof import('./components/Home.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    Movie: typeof import('./components/Movie.vue')['default']
    MovieList: typeof import('./components/MovieList.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
